# GitHub Actions: Deploy Python app to Azure Web App - stocks
name: Build and deploy Python app to Azure Web App - stocks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Habilitar repositorio universe
        run: sudo add-apt-repository universe

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev build-essential python3.10-dev python3-distutils

      - name: Configurar versión de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Actualizar pip y herramientas de construcción
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Crear entorno virtual e instalar dependencias
        run: |
          python -m venv venv
          venv/bin/python -m pip install --upgrade pip setuptools wheel
          venv/bin/python -m pip install -r requirements.txt --verbose

      - name: Verificar instalación de pyodbc
        run: |
          venv/bin/python -c "import pyodbc; print(pyodbc.version)"

      - name: Ejecutar pruebas
        run: |
          venv/bin/python -m unittest discover

      - name: Verificar contenido del directorio
        run: ls -la

      - name: Empaquetar artefacto para despliegue
        run: zip -r release.zip ./* -x "venv/*" "*.git/*" "*.github/*" "tests/*"

      - name: Subir artefacto para trabajos de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Descargar artefacto del trabajo de build
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Descomprimir artefacto para despliegue
        run: unzip release.zip

      - name: Verificar conexión con Azure Web App
        run: |
          az webapp show --name 'stocks' --resource-group 'YourResourceGroupName' --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'stocks'
          slot-name: 'Production'

      - name: Notificación de estado
        if: failure() || success()
        run: echo "El workflow finalizó con el estado ${{ job.status }}"
